### PR TITLE
Correcting a handful of spelling mistakes and grammar errors, as well as providing translation files for Portuguese (European)

### PR DESCRIPTION
**Pull request by GwynethLlewelyn**
Hi there!

I've been a user of your plugin for many, many years, and today I decided to make a small contribution... not a monetary one (sorry!) but rather some extra translation files — in Portuguese. Who knows, they might be useful...

I tried to get your permission on Transifex to add the Portuguese language directly there, but, unfortunately, it seems that I cannot be added to the team 😞 But since you so kindly put the plugin code here on GitHub and are accepting pull requests, I'm submitting them here!

I've also done a review of the *English*. This required actually changing the original translation files. Because you have an automated process with Transifex, I have no idea if the changes will actually be useful. I've also added some Markdown formatting on the `readme.txt` file... all minor changes, to be honest.

I hope you find this useful, and thanks for a plugin working so well for almost a decade now!

Cheers,

   - Gwyn

P.S. If it's not clear, I obviously release all changes & translations under the same license as your plugin, i.e. GPL2.

### CODE REVIEW

**Comment by mibuthu** [comment]
Thanks for your work.

Can you please provide a pull request with the typo and grammer fixes only? I would like to merge these parts but not all of the other changes. Some of them I will add by myself.

Regarding the translations:
Transifex should be the single source for included translation files.
I have already added Portuguese (Portugal) as requested in Transifex. I have also added you as a translator.
When you provide the seperate pull request, I will merge the changes and update the source in Transifex.
Would be great if you can then provide your translations there.

**Comment by GwynethLlewelyn** [comment]
Sorry, I have been a bit busy and haven't done what you've requested -- I hope to do so in the next few days! Also, thanks for adding me to Transifex!

**Comment by mibuthu** [comment]
As I have changed the branch names the Pull request was closed.
Because of this, I have included your spelling and grammer improvements by myself. I have also added your translations in Transifex and have added the translations in the repository.

If I have missed something or if you find any other issue feel free to open a new pull request or modify the translations in Transifex.

Thanks for your contribution.

**Comment by GwynethLlewelyn** [comment]
Aw thanks and sorry for all your trouble!

**Pull request closed without merging**
